/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmetis_JMetis */

#ifndef _Included_jmetis_JMetis
#define _Included_jmetis_JMetis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmetis_JMetis
 * Method:    METIS_PartGraphRecursiveNative
 * Signature: ([I[I[I[I[I[I[I[I[DD[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1PartGraphRecursiveNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdouble, jintArray, jintArray, jintArray);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_PartGraphKwayNative
 * Signature: ([I[I[I[I[I[I[I[I[DD[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1PartGraphKwayNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdouble, jintArray, jintArray, jintArray);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_PartMeshDualNative
 * Signature: ([I[I[I[I[I[I[I[I[D[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1PartMeshDualNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_PartMeshNodalNative
 * Signature: ([I[I[I[I[I[I[I[D[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1PartMeshNodalNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_NodeNDNative
 * Signature: ([I[I[I[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1NodeNDNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_MeshToDualNative
 * Signature: ([I[I[I[I[I[ILjmetis/MetisPointer;Ljmetis/MetisPointer;)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1MeshToDualNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jobject, jobject);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_MeshToNodalNative
 * Signature: ([I[I[I[I[ILjmetis/MetisPointer;Ljmetis/MetisPointer;)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1MeshToNodalNative
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jintArray, jobject, jobject);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_SetDefaultOptionsNative
 * Signature: (Ljmetis/MetisOptions;)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1SetDefaultOptionsNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jmetis_JMetis
 * Method:    METIS_FreeNative
 * Signature: (Ljmetis/MetisPointer;)I
 */
JNIEXPORT jint JNICALL Java_jmetis_JMetis_METIS_1FreeNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
